// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.5.1
// source: exitbattle.proto

package prvs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestExitBattleSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleSpaceID string `protobuf:"bytes,1,opt,name=BattleSpaceID,proto3" json:"BattleSpaceID,omitempty"` // 对战空间ID
	UID           string `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`                     // player uid
}

func (x *RequestExitBattleSpace) Reset() {
	*x = RequestExitBattleSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exitbattle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestExitBattleSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExitBattleSpace) ProtoMessage() {}

func (x *RequestExitBattleSpace) ProtoReflect() protoreflect.Message {
	mi := &file_exitbattle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExitBattleSpace.ProtoReflect.Descriptor instead.
func (*RequestExitBattleSpace) Descriptor() ([]byte, []int) {
	return file_exitbattle_proto_rawDescGZIP(), []int{0}
}

func (x *RequestExitBattleSpace) GetBattleSpaceID() string {
	if x != nil {
		return x.BattleSpaceID
	}
	return ""
}

func (x *RequestExitBattleSpace) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

var File_exitbattle_proto protoreflect.FileDescriptor

var file_exitbattle_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x78, 0x69, 0x74, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x70, 0x72, 0x76, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x78, 0x69, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x70, 0x72, 0x76, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exitbattle_proto_rawDescOnce sync.Once
	file_exitbattle_proto_rawDescData = file_exitbattle_proto_rawDesc
)

func file_exitbattle_proto_rawDescGZIP() []byte {
	file_exitbattle_proto_rawDescOnce.Do(func() {
		file_exitbattle_proto_rawDescData = protoimpl.X.CompressGZIP(file_exitbattle_proto_rawDescData)
	})
	return file_exitbattle_proto_rawDescData
}

var file_exitbattle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exitbattle_proto_goTypes = []interface{}{
	(*RequestExitBattleSpace)(nil), // 0: prvs.RequestExitBattleSpace
}
var file_exitbattle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exitbattle_proto_init() }
func file_exitbattle_proto_init() {
	if File_exitbattle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exitbattle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestExitBattleSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exitbattle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exitbattle_proto_goTypes,
		DependencyIndexes: file_exitbattle_proto_depIdxs,
		MessageInfos:      file_exitbattle_proto_msgTypes,
	}.Build()
	File_exitbattle_proto = out.File
	file_exitbattle_proto_rawDesc = nil
	file_exitbattle_proto_goTypes = nil
	file_exitbattle_proto_depIdxs = nil
}
