// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package prvs

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//  - BattleSpaceID
//  - UID
type RequestExitBattleSpace struct {
  BattleSpaceID string `thrift:"BattleSpaceID,1" db:"BattleSpaceID" json:"BattleSpaceID"`
  UID string `thrift:"UID,2" db:"UID" json:"UID"`
}

func NewRequestExitBattleSpace() *RequestExitBattleSpace {
  return &RequestExitBattleSpace{}
}


func (p *RequestExitBattleSpace) GetBattleSpaceID() string {
  return p.BattleSpaceID
}

func (p *RequestExitBattleSpace) GetUID() string {
  return p.UID
}
func (p *RequestExitBattleSpace) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestExitBattleSpace)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.BattleSpaceID = v
}
  return nil
}

func (p *RequestExitBattleSpace)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.UID = v
}
  return nil
}

func (p *RequestExitBattleSpace) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "RequestExitBattleSpace"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestExitBattleSpace) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "BattleSpaceID", thrift.STRING, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:BattleSpaceID: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.BattleSpaceID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.BattleSpaceID (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:BattleSpaceID: ", p), err) }
  return err
}

func (p *RequestExitBattleSpace) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "UID", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:UID: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.UID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.UID (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:UID: ", p), err) }
  return err
}

func (p *RequestExitBattleSpace) Equals(other *RequestExitBattleSpace) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.BattleSpaceID != other.BattleSpaceID { return false }
  if p.UID != other.UID { return false }
  return true
}

func (p *RequestExitBattleSpace) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestExitBattleSpace(%+v)", *p)
}

func (p *RequestExitBattleSpace) Validate() error {
  return nil
}
type RequestExitBattleSpaceService interface {
  // Parameters:
  //  - Req
  OnRequestExitBattleSpace(ctx context.Context, req *RequestExitBattleSpace) (_r *RequestExitBattleSpace, _err error)
}

type RequestExitBattleSpaceServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewRequestExitBattleSpaceServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *RequestExitBattleSpaceServiceClient {
  return &RequestExitBattleSpaceServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewRequestExitBattleSpaceServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *RequestExitBattleSpaceServiceClient {
  return &RequestExitBattleSpaceServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewRequestExitBattleSpaceServiceClient(c thrift.TClient) *RequestExitBattleSpaceServiceClient {
  return &RequestExitBattleSpaceServiceClient{
    c: c,
  }
}

func (p *RequestExitBattleSpaceServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *RequestExitBattleSpaceServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *RequestExitBattleSpaceServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// Parameters:
//  - Req
func (p *RequestExitBattleSpaceServiceClient) OnRequestExitBattleSpace(ctx context.Context, req *RequestExitBattleSpace) (_r *RequestExitBattleSpace, _err error) {
  var _args0 RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs
  _args0.Req = req
  var _result2 RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult
  var _meta1 thrift.ResponseMeta
  _meta1, _err = p.Client_().Call(ctx, "OnRequestExitBattleSpace", &_args0, &_result2)
  p.SetLastResponseMeta_(_meta1)
  if _err != nil {
    return
  }
  if _ret3 := _result2.GetSuccess(); _ret3 != nil {
    return _ret3, nil
  }
  return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "OnRequestExitBattleSpace failed: unknown result")
}

type RequestExitBattleSpaceServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler RequestExitBattleSpaceService
}

func (p *RequestExitBattleSpaceServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *RequestExitBattleSpaceServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *RequestExitBattleSpaceServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewRequestExitBattleSpaceServiceProcessor(handler RequestExitBattleSpaceService) *RequestExitBattleSpaceServiceProcessor {

  self4 := &RequestExitBattleSpaceServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self4.processorMap["OnRequestExitBattleSpace"] = &requestExitBattleSpaceServiceProcessorOnRequestExitBattleSpace{handler:handler}
return self4
}

func (p *RequestExitBattleSpaceServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x5 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x5.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x5

}

type requestExitBattleSpaceServiceProcessorOnRequestExitBattleSpace struct {
  handler RequestExitBattleSpaceService
}

func (p *requestExitBattleSpaceServiceProcessorOnRequestExitBattleSpace) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err6 error
  args := RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "OnRequestExitBattleSpace", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult{}
  if retval, err2 := p.handler.OnRequestExitBattleSpace(ctx, args.Req); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc7 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing OnRequestExitBattleSpace: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "OnRequestExitBattleSpace", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err6 = thrift.WrapTException(err2)
    }
    if err2 := _exc7.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
      _write_err6 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
      _write_err6 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
      _write_err6 = thrift.WrapTException(err2)
    }
    if _write_err6 != nil {
      return false, thrift.WrapTException(_write_err6)
    }
    return true, err
  } else {
    result.Success = retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "OnRequestExitBattleSpace", thrift.REPLY, seqId); err2 != nil {
    _write_err6 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
    _write_err6 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
    _write_err6 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
    _write_err6 = thrift.WrapTException(err2)
  }
  if _write_err6 != nil {
    return false, thrift.WrapTException(_write_err6)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
type RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs struct {
  Req *RequestExitBattleSpace `thrift:"req,1" db:"req" json:"req"`
}

func NewRequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs() *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs {
  return &RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs{}
}

var RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs_Req_DEFAULT *RequestExitBattleSpace
func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) GetReq() *RequestExitBattleSpace {
  if !p.IsSetReq() {
    return RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs_Req_DEFAULT
  }
return p.Req
}
func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &RequestExitBattleSpace{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestExitBattleSpace_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestExitBattleSpaceServiceOnRequestExitBattleSpaceArgs(%+v)", *p)
}

// Attributes:
//  - Success
type RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult struct {
  Success *RequestExitBattleSpace `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewRequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult() *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult {
  return &RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult{}
}

var RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult_Success_DEFAULT *RequestExitBattleSpace
func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) GetSuccess() *RequestExitBattleSpace {
  if !p.IsSetSuccess() {
    return RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult_Success_DEFAULT
  }
return p.Success
}
func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  p.Success = &RequestExitBattleSpace{}
  if err := p.Success.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestExitBattleSpace_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestExitBattleSpaceServiceOnRequestExitBattleSpaceResult(%+v)", *p)
}


