/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{
  public static class battle_serviceExtensions
  {
    public static bool Equals(this List<global::protocols.pubs.BattleSpaceDataSimple> instance, object that)
    {
      if (!(that is List<global::protocols.pubs.BattleSpaceDataSimple> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::protocols.pubs.BattleSpaceDataSimple> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::protocols.pubs.BattleSpaceDataSimple> DeepCopy(this List<global::protocols.pubs.BattleSpaceDataSimple> source)
    {
      if (source == null)
        return null;

      var tmp114 = new List<global::protocols.pubs.BattleSpaceDataSimple>(source.Count);
      foreach (var elem in source)
        tmp114.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp114;
    }


    public static bool Equals(this List<global::protocols.pubs.BattleSpacePlayer> instance, object that)
    {
      if (!(that is List<global::protocols.pubs.BattleSpacePlayer> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::protocols.pubs.BattleSpacePlayer> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::protocols.pubs.BattleSpacePlayer> DeepCopy(this List<global::protocols.pubs.BattleSpacePlayer> source)
    {
      if (source == null)
        return null;

      var tmp115 = new List<global::protocols.pubs.BattleSpacePlayer>(source.Count);
      foreach (var elem in source)
        tmp115.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp115;
    }


    public static bool Equals(this List<global::protocols.pubs.BattleSpacePlayerSimple> instance, object that)
    {
      if (!(that is List<global::protocols.pubs.BattleSpacePlayerSimple> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::protocols.pubs.BattleSpacePlayerSimple> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::protocols.pubs.BattleSpacePlayerSimple> DeepCopy(this List<global::protocols.pubs.BattleSpacePlayerSimple> source)
    {
      if (source == null)
        return null;

      var tmp116 = new List<global::protocols.pubs.BattleSpacePlayerSimple>(source.Count);
      foreach (var elem in source)
        tmp116.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp116;
    }


  }
}
