/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{

  public partial class CreateBattleSpace : TBase
  {
    private string _mapURI;
    private int _maxCount;

    public string MapURI
    {
      get
      {
        return _mapURI;
      }
      set
      {
        __isset.mapURI = true;
        this._mapURI = value;
      }
    }

    public int MaxCount
    {
      get
      {
        return _maxCount;
      }
      set
      {
        __isset.maxCount = true;
        this._maxCount = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool mapURI;
      public bool maxCount;
    }

    public CreateBattleSpace()
    {
    }

    public CreateBattleSpace DeepCopy()
    {
      var tmp0 = new CreateBattleSpace();
      if((MapURI != null) && __isset.mapURI)
      {
        tmp0.MapURI = this.MapURI;
      }
      tmp0.__isset.mapURI = this.__isset.mapURI;
      if(__isset.maxCount)
      {
        tmp0.MaxCount = this.MaxCount;
      }
      tmp0.__isset.maxCount = this.__isset.maxCount;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                MapURI = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                MaxCount = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp1 = new TStruct("CreateBattleSpace");
        await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
        var tmp2 = new TField();
        if((MapURI != null) && __isset.mapURI)
        {
          tmp2.Name = "mapURI";
          tmp2.Type = TType.String;
          tmp2.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteStringAsync(MapURI, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.maxCount)
        {
          tmp2.Name = "maxCount";
          tmp2.Type = TType.I32;
          tmp2.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteI32Async(MaxCount, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is CreateBattleSpace other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.mapURI == other.__isset.mapURI) && ((!__isset.mapURI) || (global::System.Object.Equals(MapURI, other.MapURI))))
        && ((__isset.maxCount == other.__isset.maxCount) && ((!__isset.maxCount) || (global::System.Object.Equals(MaxCount, other.MaxCount))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((MapURI != null) && __isset.mapURI)
        {
          hashcode = (hashcode * 397) + MapURI.GetHashCode();
        }
        if(__isset.maxCount)
        {
          hashcode = (hashcode * 397) + MaxCount.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp3 = new StringBuilder("CreateBattleSpace(");
      int tmp4 = 0;
      if((MapURI != null) && __isset.mapURI)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("MapURI: ");
        MapURI.ToString(tmp3);
      }
      if(__isset.maxCount)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("MaxCount: ");
        MaxCount.ToString(tmp3);
      }
      tmp3.Append(')');
      return tmp3.ToString();
    }
  }

}
