/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{

  public partial class EnterBattleSpaceResp : TBase
  {
    private global::protocols.pubs.BattleSpaceData _space;

    public global::protocols.pubs.BattleSpaceData Space
    {
      get
      {
        return _space;
      }
      set
      {
        __isset.@space = true;
        this._space = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool @space;
    }

    public EnterBattleSpaceResp()
    {
    }

    public EnterBattleSpaceResp DeepCopy()
    {
      var tmp57 = new EnterBattleSpaceResp();
      if((Space != null) && __isset.@space)
      {
        tmp57.Space = (global::protocols.pubs.BattleSpaceData)this.Space.DeepCopy();
      }
      tmp57.__isset.@space = this.__isset.@space;
      return tmp57;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                Space = new global::protocols.pubs.BattleSpaceData();
                await Space.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp58 = new TStruct("EnterBattleSpaceResp");
        await oprot.WriteStructBeginAsync(tmp58, cancellationToken);
        var tmp59 = new TField();
        if((Space != null) && __isset.@space)
        {
          tmp59.Name = "space";
          tmp59.Type = TType.Struct;
          tmp59.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp59, cancellationToken);
          await Space.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is EnterBattleSpaceResp other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.@space == other.__isset.@space) && ((!__isset.@space) || (global::System.Object.Equals(Space, other.Space))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Space != null) && __isset.@space)
        {
          hashcode = (hashcode * 397) + Space.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp60 = new StringBuilder("EnterBattleSpaceResp(");
      int tmp61 = 0;
      if((Space != null) && __isset.@space)
      {
        if(0 < tmp61++) { tmp60.Append(", "); }
        tmp60.Append("Space: ");
        Space.ToString(tmp60);
      }
      tmp60.Append(')');
      return tmp60.ToString();
    }
  }

}
