/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{

  public partial class ExitBattleSpace : TBase
  {
    private string _spaceId;
    private string _uid;

    public string SpaceId
    {
      get
      {
        return _spaceId;
      }
      set
      {
        __isset.spaceId = true;
        this._spaceId = value;
      }
    }

    public string Uid
    {
      get
      {
        return _uid;
      }
      set
      {
        __isset.@uid = true;
        this._uid = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool spaceId;
      public bool @uid;
    }

    public ExitBattleSpace()
    {
    }

    public ExitBattleSpace DeepCopy()
    {
      var tmp62 = new ExitBattleSpace();
      if((SpaceId != null) && __isset.spaceId)
      {
        tmp62.SpaceId = this.SpaceId;
      }
      tmp62.__isset.spaceId = this.__isset.spaceId;
      if((Uid != null) && __isset.@uid)
      {
        tmp62.Uid = this.Uid;
      }
      tmp62.__isset.@uid = this.__isset.@uid;
      return tmp62;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                SpaceId = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Uid = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp63 = new TStruct("ExitBattleSpace");
        await oprot.WriteStructBeginAsync(tmp63, cancellationToken);
        var tmp64 = new TField();
        if((SpaceId != null) && __isset.spaceId)
        {
          tmp64.Name = "spaceId";
          tmp64.Type = TType.String;
          tmp64.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp64, cancellationToken);
          await oprot.WriteStringAsync(SpaceId, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Uid != null) && __isset.@uid)
        {
          tmp64.Name = "uid";
          tmp64.Type = TType.String;
          tmp64.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp64, cancellationToken);
          await oprot.WriteStringAsync(Uid, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ExitBattleSpace other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.spaceId == other.__isset.spaceId) && ((!__isset.spaceId) || (global::System.Object.Equals(SpaceId, other.SpaceId))))
        && ((__isset.@uid == other.__isset.@uid) && ((!__isset.@uid) || (global::System.Object.Equals(Uid, other.Uid))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((SpaceId != null) && __isset.spaceId)
        {
          hashcode = (hashcode * 397) + SpaceId.GetHashCode();
        }
        if((Uid != null) && __isset.@uid)
        {
          hashcode = (hashcode * 397) + Uid.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp65 = new StringBuilder("ExitBattleSpace(");
      int tmp66 = 0;
      if((SpaceId != null) && __isset.spaceId)
      {
        if(0 < tmp66++) { tmp65.Append(", "); }
        tmp65.Append("SpaceId: ");
        SpaceId.ToString(tmp65);
      }
      if((Uid != null) && __isset.@uid)
      {
        if(0 < tmp66++) { tmp65.Append(", "); }
        tmp65.Append("Uid: ");
        Uid.ToString(tmp65);
      }
      tmp65.Append(')');
      return tmp65.ToString();
    }
  }

}
