/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{

  public partial class GetBattleSpaceList : TBase
  {
    private int _start;
    private int _size;

    public int Start
    {
      get
      {
        return _start;
      }
      set
      {
        __isset.@start = true;
        this._start = value;
      }
    }

    public int Size
    {
      get
      {
        return _size;
      }
      set
      {
        __isset.@size = true;
        this._size = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool @start;
      public bool @size;
    }

    public GetBattleSpaceList()
    {
    }

    public GetBattleSpaceList DeepCopy()
    {
      var tmp38 = new GetBattleSpaceList();
      if(__isset.@start)
      {
        tmp38.Start = this.Start;
      }
      tmp38.__isset.@start = this.__isset.@start;
      if(__isset.@size)
      {
        tmp38.Size = this.Size;
      }
      tmp38.__isset.@size = this.__isset.@size;
      return tmp38;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Start = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I32)
              {
                Size = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp39 = new TStruct("GetBattleSpaceList");
        await oprot.WriteStructBeginAsync(tmp39, cancellationToken);
        var tmp40 = new TField();
        if(__isset.@start)
        {
          tmp40.Name = "start";
          tmp40.Type = TType.I32;
          tmp40.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
          await oprot.WriteI32Async(Start, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.@size)
        {
          tmp40.Name = "size";
          tmp40.Type = TType.I32;
          tmp40.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp40, cancellationToken);
          await oprot.WriteI32Async(Size, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is GetBattleSpaceList other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.@start == other.__isset.@start) && ((!__isset.@start) || (global::System.Object.Equals(Start, other.Start))))
        && ((__isset.@size == other.__isset.@size) && ((!__isset.@size) || (global::System.Object.Equals(Size, other.Size))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.@start)
        {
          hashcode = (hashcode * 397) + Start.GetHashCode();
        }
        if(__isset.@size)
        {
          hashcode = (hashcode * 397) + Size.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp41 = new StringBuilder("GetBattleSpaceList(");
      int tmp42 = 0;
      if(__isset.@start)
      {
        if(0 < tmp42++) { tmp41.Append(", "); }
        tmp41.Append("Start: ");
        Start.ToString(tmp41);
      }
      if(__isset.@size)
      {
        if(0 < tmp42++) { tmp41.Append(", "); }
        tmp41.Append("Size: ");
        Size.ToString(tmp41);
      }
      tmp41.Append(')');
      return tmp41.ToString();
    }
  }

}
