/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{
  public partial class LoginService
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task<global::protocols.pubs.SignInResp> OnSignIn(global::protocols.pubs.SignIn @req, CancellationToken cancellationToken = default);

      global::System.Threading.Tasks.Task<global::protocols.pubs.SignOutResp> OnSignOut(global::protocols.pubs.SignOut @req, CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)
      {
      }

      public async global::System.Threading.Tasks.Task<global::protocols.pubs.SignInResp> OnSignIn(global::protocols.pubs.SignIn @req, CancellationToken cancellationToken = default)
      {
        await send_OnSignIn(@req, cancellationToken);
        return await recv_OnSignIn(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_OnSignIn(global::protocols.pubs.SignIn @req, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("OnSignIn", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp0 = new InternalStructs.OnSignIn_args() {
          Req = @req,
        };
        
        await tmp0.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<global::protocols.pubs.SignInResp> recv_OnSignIn(CancellationToken cancellationToken = default)
      {
        
        var tmp1 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp1.Type == TMessageType.Exception)
        {
          var tmp2 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp2;
        }

        var tmp3 = new InternalStructs.OnSignIn_result();
        await tmp3.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp3.__isset.success)
        {
          return tmp3.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "OnSignIn failed: unknown result");
      }

      public async global::System.Threading.Tasks.Task<global::protocols.pubs.SignOutResp> OnSignOut(global::protocols.pubs.SignOut @req, CancellationToken cancellationToken = default)
      {
        await send_OnSignOut(@req, cancellationToken);
        return await recv_OnSignOut(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_OnSignOut(global::protocols.pubs.SignOut @req, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("OnSignOut", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp4 = new InternalStructs.OnSignOut_args() {
          Req = @req,
        };
        
        await tmp4.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<global::protocols.pubs.SignOutResp> recv_OnSignOut(CancellationToken cancellationToken = default)
      {
        
        var tmp5 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp5.Type == TMessageType.Exception)
        {
          var tmp6 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp6;
        }

        var tmp7 = new InternalStructs.OnSignOut_result();
        await tmp7.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp7.__isset.success)
        {
          return tmp7.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "OnSignOut failed: unknown result");
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["OnSignIn"] = OnSignIn_ProcessAsync;
        processMap_["OnSignOut"] = OnSignOut_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out var fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task OnSignIn_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp8 = new InternalStructs.OnSignIn_args();
        await tmp8.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp9 = new InternalStructs.OnSignIn_result();
        try
        {
          tmp9.Success = await _iAsync.OnSignIn(tmp8.Req, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("OnSignIn", TMessageType.Reply, seqid), cancellationToken); 
          await tmp9.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp10)
        {
          var tmp11 = $"Error occurred in {GetType().FullName}: {tmp10.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp10, tmp11);
          else
            Console.Error.WriteLine(tmp11);
          var tmp12 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("OnSignIn", TMessageType.Exception, seqid), cancellationToken);
          await tmp12.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task OnSignOut_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp13 = new InternalStructs.OnSignOut_args();
        await tmp13.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp14 = new InternalStructs.OnSignOut_result();
        try
        {
          tmp14.Success = await _iAsync.OnSignOut(tmp13.Req, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("OnSignOut", TMessageType.Reply, seqid), cancellationToken); 
          await tmp14.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp15)
        {
          var tmp16 = $"Error occurred in {GetType().FullName}: {tmp15.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp15, tmp16);
          else
            Console.Error.WriteLine(tmp16);
          var tmp17 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("OnSignOut", TMessageType.Exception, seqid), cancellationToken);
          await tmp17.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class OnSignIn_args : TBase
      {
        private global::protocols.pubs.SignIn _req;

        public global::protocols.pubs.SignIn Req
        {
          get
          {
            return _req;
          }
          set
          {
            __isset.@req = true;
            this._req = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @req;
        }

        public OnSignIn_args()
        {
        }

        public OnSignIn_args DeepCopy()
        {
          var tmp18 = new OnSignIn_args();
          if((Req != null) && __isset.@req)
          {
            tmp18.Req = (global::protocols.pubs.SignIn)this.Req.DeepCopy();
          }
          tmp18.__isset.@req = this.__isset.@req;
          return tmp18;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.Struct)
                  {
                    Req = new global::protocols.pubs.SignIn();
                    await Req.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp19 = new TStruct("OnSignIn_args");
            await oprot.WriteStructBeginAsync(tmp19, cancellationToken);
            var tmp20 = new TField();
            if((Req != null) && __isset.@req)
            {
              tmp20.Name = "req";
              tmp20.Type = TType.Struct;
              tmp20.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp20, cancellationToken);
              await Req.WriteAsync(oprot, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is OnSignIn_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@req == other.__isset.@req) && ((!__isset.@req) || (global::System.Object.Equals(Req, other.Req))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Req != null) && __isset.@req)
            {
              hashcode = (hashcode * 397) + Req.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp21 = new StringBuilder("OnSignIn_args(");
          int tmp22 = 0;
          if((Req != null) && __isset.@req)
          {
            if(0 < tmp22++) { tmp21.Append(", "); }
            tmp21.Append("Req: ");
            Req.ToString(tmp21);
          }
          tmp21.Append(')');
          return tmp21.ToString();
        }
      }


      public partial class OnSignIn_result : TBase
      {
        private global::protocols.pubs.SignInResp _success;

        public global::protocols.pubs.SignInResp Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public OnSignIn_result()
        {
        }

        public OnSignIn_result DeepCopy()
        {
          var tmp23 = new OnSignIn_result();
          if((Success != null) && __isset.@success)
          {
            tmp23.Success = (global::protocols.pubs.SignInResp)this.Success.DeepCopy();
          }
          tmp23.__isset.@success = this.__isset.@success;
          return tmp23;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.Struct)
                  {
                    Success = new global::protocols.pubs.SignInResp();
                    await Success.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp24 = new TStruct("OnSignIn_result");
            await oprot.WriteStructBeginAsync(tmp24, cancellationToken);
            var tmp25 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp25.Name = "Success";
                tmp25.Type = TType.Struct;
                tmp25.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp25, cancellationToken);
                await Success.WriteAsync(oprot, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is OnSignIn_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp26 = new StringBuilder("OnSignIn_result(");
          int tmp27 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp27++) { tmp26.Append(", "); }
            tmp26.Append("Success: ");
            Success.ToString(tmp26);
          }
          tmp26.Append(')');
          return tmp26.ToString();
        }
      }


      public partial class OnSignOut_args : TBase
      {
        private global::protocols.pubs.SignOut _req;

        public global::protocols.pubs.SignOut Req
        {
          get
          {
            return _req;
          }
          set
          {
            __isset.@req = true;
            this._req = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @req;
        }

        public OnSignOut_args()
        {
        }

        public OnSignOut_args DeepCopy()
        {
          var tmp28 = new OnSignOut_args();
          if((Req != null) && __isset.@req)
          {
            tmp28.Req = (global::protocols.pubs.SignOut)this.Req.DeepCopy();
          }
          tmp28.__isset.@req = this.__isset.@req;
          return tmp28;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.Struct)
                  {
                    Req = new global::protocols.pubs.SignOut();
                    await Req.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp29 = new TStruct("OnSignOut_args");
            await oprot.WriteStructBeginAsync(tmp29, cancellationToken);
            var tmp30 = new TField();
            if((Req != null) && __isset.@req)
            {
              tmp30.Name = "req";
              tmp30.Type = TType.Struct;
              tmp30.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp30, cancellationToken);
              await Req.WriteAsync(oprot, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is OnSignOut_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@req == other.__isset.@req) && ((!__isset.@req) || (global::System.Object.Equals(Req, other.Req))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Req != null) && __isset.@req)
            {
              hashcode = (hashcode * 397) + Req.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp31 = new StringBuilder("OnSignOut_args(");
          int tmp32 = 0;
          if((Req != null) && __isset.@req)
          {
            if(0 < tmp32++) { tmp31.Append(", "); }
            tmp31.Append("Req: ");
            Req.ToString(tmp31);
          }
          tmp31.Append(')');
          return tmp31.ToString();
        }
      }


      public partial class OnSignOut_result : TBase
      {
        private global::protocols.pubs.SignOutResp _success;

        public global::protocols.pubs.SignOutResp Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public OnSignOut_result()
        {
        }

        public OnSignOut_result DeepCopy()
        {
          var tmp33 = new OnSignOut_result();
          if((Success != null) && __isset.@success)
          {
            tmp33.Success = (global::protocols.pubs.SignOutResp)this.Success.DeepCopy();
          }
          tmp33.__isset.@success = this.__isset.@success;
          return tmp33;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.Struct)
                  {
                    Success = new global::protocols.pubs.SignOutResp();
                    await Success.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp34 = new TStruct("OnSignOut_result");
            await oprot.WriteStructBeginAsync(tmp34, cancellationToken);
            var tmp35 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp35.Name = "Success";
                tmp35.Type = TType.Struct;
                tmp35.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp35, cancellationToken);
                await Success.WriteAsync(oprot, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is OnSignOut_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp36 = new StringBuilder("OnSignOut_result(");
          int tmp37 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp37++) { tmp36.Append(", "); }
            tmp36.Append("Success: ");
            Success.ToString(tmp36);
          }
          tmp36.Append(')');
          return tmp36.ToString();
        }
      }

    }

  }
}
