/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace protocols.pubs
{

  public partial class ReportNatClient : TBase
  {
    private string _BattleSpaceID;
    private string _VerifiyCode;

    public string BattleSpaceID
    {
      get
      {
        return _BattleSpaceID;
      }
      set
      {
        __isset.BattleSpaceID = true;
        this._BattleSpaceID = value;
      }
    }

    public string VerifiyCode
    {
      get
      {
        return _VerifiyCode;
      }
      set
      {
        __isset.VerifiyCode = true;
        this._VerifiyCode = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool BattleSpaceID;
      public bool VerifiyCode;
    }

    public ReportNatClient()
    {
    }

    public ReportNatClient DeepCopy()
    {
      var tmp0 = new ReportNatClient();
      if((BattleSpaceID != null) && __isset.BattleSpaceID)
      {
        tmp0.BattleSpaceID = this.BattleSpaceID;
      }
      tmp0.__isset.BattleSpaceID = this.__isset.BattleSpaceID;
      if((VerifiyCode != null) && __isset.VerifiyCode)
      {
        tmp0.VerifiyCode = this.VerifiyCode;
      }
      tmp0.__isset.VerifiyCode = this.__isset.VerifiyCode;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String)
              {
                BattleSpaceID = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                VerifiyCode = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp1 = new TStruct("ReportNatClient");
        await oprot.WriteStructBeginAsync(tmp1, cancellationToken);
        var tmp2 = new TField();
        if((BattleSpaceID != null) && __isset.BattleSpaceID)
        {
          tmp2.Name = "BattleSpaceID";
          tmp2.Type = TType.String;
          tmp2.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteStringAsync(BattleSpaceID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((VerifiyCode != null) && __isset.VerifiyCode)
        {
          tmp2.Name = "VerifiyCode";
          tmp2.Type = TType.String;
          tmp2.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp2, cancellationToken);
          await oprot.WriteStringAsync(VerifiyCode, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ReportNatClient other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.BattleSpaceID == other.__isset.BattleSpaceID) && ((!__isset.BattleSpaceID) || (global::System.Object.Equals(BattleSpaceID, other.BattleSpaceID))))
        && ((__isset.VerifiyCode == other.__isset.VerifiyCode) && ((!__isset.VerifiyCode) || (global::System.Object.Equals(VerifiyCode, other.VerifiyCode))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((BattleSpaceID != null) && __isset.BattleSpaceID)
        {
          hashcode = (hashcode * 397) + BattleSpaceID.GetHashCode();
        }
        if((VerifiyCode != null) && __isset.VerifiyCode)
        {
          hashcode = (hashcode * 397) + VerifiyCode.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp3 = new StringBuilder("ReportNatClient(");
      int tmp4 = 0;
      if((BattleSpaceID != null) && __isset.BattleSpaceID)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("BattleSpaceID: ");
        BattleSpaceID.ToString(tmp3);
      }
      if((VerifiyCode != null) && __isset.VerifiyCode)
      {
        if(0 < tmp4++) { tmp3.Append(", "); }
        tmp3.Append("VerifiyCode: ");
        VerifiyCode.ToString(tmp3);
      }
      tmp3.Append(')');
      return tmp3.ToString();
    }
  }

}
