// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: parallel/proto/messages.proto

package parallel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResumeMailbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResumeMailbox) Reset() {
	*x = ResumeMailbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeMailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeMailbox) ProtoMessage() {}

func (x *ResumeMailbox) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeMailbox.ProtoReflect.Descriptor instead.
func (*ResumeMailbox) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{0}
}

type SuspendMailbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SuspendMailbox) Reset() {
	*x = SuspendMailbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspendMailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendMailbox) ProtoMessage() {}

func (x *SuspendMailbox) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendMailbox.ProtoReflect.Descriptor instead.
func (*SuspendMailbox) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{1}
}

type ReceiveTimeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReceiveTimeout) Reset() {
	*x = ReceiveTimeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTimeout) ProtoMessage() {}

func (x *ReceiveTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTimeout.ProtoReflect.Descriptor instead.
func (*ReceiveTimeout) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{2}
}

type Restarting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Restarting) Reset() {
	*x = Restarting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Restarting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restarting) ProtoMessage() {}

func (x *Restarting) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restarting.ProtoReflect.Descriptor instead.
func (*Restarting) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{3}
}

type Stopping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stopping) Reset() {
	*x = Stopping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stopping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stopping) ProtoMessage() {}

func (x *Stopping) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stopping.ProtoReflect.Descriptor instead.
func (*Stopping) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{4}
}

type Stopped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stopped) Reset() {
	*x = Stopped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stopped) ProtoMessage() {}

func (x *Stopped) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stopped.ProtoReflect.Descriptor instead.
func (*Stopped) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{5}
}

type Started struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Started) Reset() {
	*x = Started{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{6}
}

type Restart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Restart) Reset() {
	*x = Restart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parallel_proto_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Restart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restart) ProtoMessage() {}

func (x *Restart) ProtoReflect() protoreflect.Message {
	mi := &file_parallel_proto_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restart.ProtoReflect.Descriptor instead.
func (*Restart) Descriptor() ([]byte, []int) {
	return file_parallel_proto_messages_proto_rawDescGZIP(), []int{7}
}

var File_parallel_proto_messages_proto protoreflect.FileDescriptor

var file_parallel_proto_messages_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x22, 0x10, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x0c,
	0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x0a, 0x0a, 0x08,
	0x53, 0x74, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70,
	0x70, 0x65, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x09,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70,
	0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parallel_proto_messages_proto_rawDescOnce sync.Once
	file_parallel_proto_messages_proto_rawDescData = file_parallel_proto_messages_proto_rawDesc
)

func file_parallel_proto_messages_proto_rawDescGZIP() []byte {
	file_parallel_proto_messages_proto_rawDescOnce.Do(func() {
		file_parallel_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_parallel_proto_messages_proto_rawDescData)
	})
	return file_parallel_proto_messages_proto_rawDescData
}

var file_parallel_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_parallel_proto_messages_proto_goTypes = []interface{}{
	(*ResumeMailbox)(nil),  // 0: parallel.ResumeMailbox
	(*SuspendMailbox)(nil), // 1: parallel.SuspendMailbox
	(*ReceiveTimeout)(nil), // 2: parallel.ReceiveTimeout
	(*Restarting)(nil),     // 3: parallel.Restarting
	(*Stopping)(nil),       // 4: parallel.Stopping
	(*Stopped)(nil),        // 5: parallel.Stopped
	(*Started)(nil),        // 6: parallel.Started
	(*Restart)(nil),        // 7: parallel.Restart
}
var file_parallel_proto_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parallel_proto_messages_proto_init() }
func file_parallel_proto_messages_proto_init() {
	if File_parallel_proto_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parallel_proto_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeMailbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspendMailbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveTimeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Restarting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stopping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stopped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Started); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parallel_proto_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Restart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parallel_proto_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parallel_proto_messages_proto_goTypes,
		DependencyIndexes: file_parallel_proto_messages_proto_depIdxs,
		MessageInfos:      file_parallel_proto_messages_proto_msgTypes,
	}.Build()
	File_parallel_proto_messages_proto = out.File
	file_parallel_proto_messages_proto_rawDesc = nil
	file_parallel_proto_messages_proto_goTypes = nil
	file_parallel_proto_messages_proto_depIdxs = nil
}
