// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: require_nat.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 要求客户端发送Nat报告
type RequireNat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID      uint32 `protobuf:"fixed32,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`         // 房间ID
	VerifiyCode string `protobuf:"bytes,2,opt,name=VerifiyCode,proto3" json:"VerifiyCode,omitempty"` // 房间验证码
}

func (x *RequireNat) Reset() {
	*x = RequireNat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_require_nat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireNat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireNat) ProtoMessage() {}

func (x *RequireNat) ProtoReflect() protoreflect.Message {
	mi := &file_require_nat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireNat.ProtoReflect.Descriptor instead.
func (*RequireNat) Descriptor() ([]byte, []int) {
	return file_require_nat_proto_rawDescGZIP(), []int{0}
}

func (x *RequireNat) GetRoomID() uint32 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *RequireNat) GetVerifiyCode() string {
	if x != nil {
		return x.VerifiyCode
	}
	return ""
}

var File_require_nat_proto protoreflect.FileDescriptor

var file_require_nat_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x22, 0x46,
	0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x4e, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_require_nat_proto_rawDescOnce sync.Once
	file_require_nat_proto_rawDescData = file_require_nat_proto_rawDesc
)

func file_require_nat_proto_rawDescGZIP() []byte {
	file_require_nat_proto_rawDescOnce.Do(func() {
		file_require_nat_proto_rawDescData = protoimpl.X.CompressGZIP(file_require_nat_proto_rawDescData)
	})
	return file_require_nat_proto_rawDescData
}

var file_require_nat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_require_nat_proto_goTypes = []interface{}{
	(*RequireNat)(nil), // 0: protocols.RequireNat
}
var file_require_nat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_require_nat_proto_init() }
func file_require_nat_proto_init() {
	if File_require_nat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_require_nat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireNat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_require_nat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_require_nat_proto_goTypes,
		DependencyIndexes: file_require_nat_proto_depIdxs,
		MessageInfos:      file_require_nat_proto_msgTypes,
	}.Build()
	File_require_nat_proto = out.File
	file_require_nat_proto_rawDesc = nil
	file_require_nat_proto_goTypes = nil
	file_require_nat_proto_depIdxs = nil
}
