// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: closing.proto

package protocols

import (
	network "github.com/yamakiller/velcro-go/network"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 要求关闭某客户端套接子
type Closing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID *network.ClientID `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
}

func (x *Closing) Reset() {
	*x = Closing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_closing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Closing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Closing) ProtoMessage() {}

func (x *Closing) ProtoReflect() protoreflect.Message {
	mi := &file_closing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Closing.ProtoReflect.Descriptor instead.
func (*Closing) Descriptor() ([]byte, []int) {
	return file_closing_proto_rawDescGZIP(), []int{0}
}

func (x *Closing) GetClientID() *network.ClientID {
	if x != nil {
		return x.ClientID
	}
	return nil
}

var File_closing_proto protoreflect.FileDescriptor

var file_closing_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x0f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x07, 0x43,
	0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_closing_proto_rawDescOnce sync.Once
	file_closing_proto_rawDescData = file_closing_proto_rawDesc
)

func file_closing_proto_rawDescGZIP() []byte {
	file_closing_proto_rawDescOnce.Do(func() {
		file_closing_proto_rawDescData = protoimpl.X.CompressGZIP(file_closing_proto_rawDescData)
	})
	return file_closing_proto_rawDescData
}

var file_closing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_closing_proto_goTypes = []interface{}{
	(*Closing)(nil),          // 0: protocols.Closing
	(*network.ClientID)(nil), // 1: network.ClientID
}
var file_closing_proto_depIdxs = []int32{
	1, // 0: protocols.Closing.ClientID:type_name -> network.ClientID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_closing_proto_init() }
func file_closing_proto_init() {
	if File_closing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_closing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Closing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_closing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_closing_proto_goTypes,
		DependencyIndexes: file_closing_proto_depIdxs,
		MessageInfos:      file_closing_proto_msgTypes,
	}.Build()
	File_closing_proto = out.File
	file_closing_proto_rawDesc = nil
	file_closing_proto_goTypes = nil
	file_closing_proto_depIdxs = nil
}
