// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package prvs

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
  "github.com/yamakiller/velcro-go/network"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//  - Target
//  - Rule
type RequestGatewayAlterRule struct {
  Target *network.ClientID `thrift:"target,1" db:"target" json:"target"`
  Rule int32 `thrift:"Rule,2" db:"Rule" json:"Rule"`
}

func NewRequestGatewayAlterRule() *RequestGatewayAlterRule {
  return &RequestGatewayAlterRule{}
}

var RequestGatewayAlterRule_Target_DEFAULT *network.ClientID
func (p *RequestGatewayAlterRule) GetTarget() *network.ClientID {
  if !p.IsSetTarget() {
    return RequestGatewayAlterRule_Target_DEFAULT
  }
return p.Target
}

func (p *RequestGatewayAlterRule) GetRule() int32 {
  return p.Rule
}
func (p *RequestGatewayAlterRule) IsSetTarget() bool {
  return p.Target != nil
}

func (p *RequestGatewayAlterRule) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayAlterRule)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Target = &network.ClientID{}
  if err := p.Target.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Target), err)
  }
  return nil
}

func (p *RequestGatewayAlterRule)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Rule = v
}
  return nil
}

func (p *RequestGatewayAlterRule) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "RequestGatewayAlterRule"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayAlterRule) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "target", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:target: ", p), err) }
  if err := p.Target.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Target), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:target: ", p), err) }
  return err
}

func (p *RequestGatewayAlterRule) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "Rule", thrift.I32, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:Rule: ", p), err) }
  if err := oprot.WriteI32(ctx, int32(p.Rule)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.Rule (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:Rule: ", p), err) }
  return err
}

func (p *RequestGatewayAlterRule) Equals(other *RequestGatewayAlterRule) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if !p.Target.Equals(other.Target) { return false }
  if p.Rule != other.Rule { return false }
  return true
}

func (p *RequestGatewayAlterRule) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayAlterRule(%+v)", *p)
}

func (p *RequestGatewayAlterRule) Validate() error {
  return nil
}
type RequestGatewayAlterRuleService interface {
  // Parameters:
  //  - Req
  OnRequestGatewayAlterRule(ctx context.Context, req *RequestGatewayAlterRule) (_err error)
}

type RequestGatewayAlterRuleServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewRequestGatewayAlterRuleServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *RequestGatewayAlterRuleServiceClient {
  return &RequestGatewayAlterRuleServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewRequestGatewayAlterRuleServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *RequestGatewayAlterRuleServiceClient {
  return &RequestGatewayAlterRuleServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewRequestGatewayAlterRuleServiceClient(c thrift.TClient) *RequestGatewayAlterRuleServiceClient {
  return &RequestGatewayAlterRuleServiceClient{
    c: c,
  }
}

func (p *RequestGatewayAlterRuleServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *RequestGatewayAlterRuleServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *RequestGatewayAlterRuleServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// Parameters:
//  - Req
func (p *RequestGatewayAlterRuleServiceClient) OnRequestGatewayAlterRule(ctx context.Context, req *RequestGatewayAlterRule) (_err error) {
  var _args0 RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs
  _args0.Req = req
  var _result2 RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult
  var _meta1 thrift.ResponseMeta
  _meta1, _err = p.Client_().Call(ctx, "OnRequestGatewayAlterRule", &_args0, &_result2)
  p.SetLastResponseMeta_(_meta1)
  if _err != nil {
    return
  }
  return nil
}

type RequestGatewayAlterRuleServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler RequestGatewayAlterRuleService
}

func (p *RequestGatewayAlterRuleServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *RequestGatewayAlterRuleServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *RequestGatewayAlterRuleServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewRequestGatewayAlterRuleServiceProcessor(handler RequestGatewayAlterRuleService) *RequestGatewayAlterRuleServiceProcessor {

  self3 := &RequestGatewayAlterRuleServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self3.processorMap["OnRequestGatewayAlterRule"] = &requestGatewayAlterRuleServiceProcessorOnRequestGatewayAlterRule{handler:handler}
return self3
}

func (p *RequestGatewayAlterRuleServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x4 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x4.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x4

}

type requestGatewayAlterRuleServiceProcessorOnRequestGatewayAlterRule struct {
  handler RequestGatewayAlterRuleService
}

func (p *requestGatewayAlterRuleServiceProcessorOnRequestGatewayAlterRule) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err5 error
  args := RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "OnRequestGatewayAlterRule", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult{}
  if err2 := p.handler.OnRequestGatewayAlterRule(ctx, args.Req); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc6 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing OnRequestGatewayAlterRule: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "OnRequestGatewayAlterRule", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := _exc6.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if _write_err5 != nil {
      return false, thrift.WrapTException(_write_err5)
    }
    return true, err
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "OnRequestGatewayAlterRule", thrift.REPLY, seqId); err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if _write_err5 != nil {
    return false, thrift.WrapTException(_write_err5)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
type RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs struct {
  Req *RequestGatewayAlterRule `thrift:"req,1" db:"req" json:"req"`
}

func NewRequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs() *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs {
  return &RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs{}
}

var RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs_Req_DEFAULT *RequestGatewayAlterRule
func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) GetReq() *RequestGatewayAlterRule {
  if !p.IsSetReq() {
    return RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs_Req_DEFAULT
  }
return p.Req
}
func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &RequestGatewayAlterRule{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestGatewayAlterRule_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleArgs(%+v)", *p)
}

type RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult struct {
}

func NewRequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult() *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult {
  return &RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult{}
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(ctx, fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestGatewayAlterRule_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayAlterRuleServiceOnRequestGatewayAlterRuleResult(%+v)", *p)
}


