// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.5.1
// source: bundle.proto

package prvs

import (
	any "github.com/golang/protobuf/ptypes/any"
	network "github.com/yamakiller/velcro-go/network"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务->网关->客户端
type ForwardBundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender *network.ClientID `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // 目标(可为空)
	Body   *any.Any          `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`     // 具体消息
}

func (x *ForwardBundle) Reset() {
	*x = ForwardBundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bundle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardBundle) ProtoMessage() {}

func (x *ForwardBundle) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardBundle.ProtoReflect.Descriptor instead.
func (*ForwardBundle) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardBundle) GetSender() *network.ClientID {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *ForwardBundle) GetBody() *any.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

// 服务->网关->客户端
type RequestGatewayPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *network.ClientID `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // 目标(可为空)
	Body   *any.Any          `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`     // 具体消息
}

func (x *RequestGatewayPush) Reset() {
	*x = RequestGatewayPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bundle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGatewayPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGatewayPush) ProtoMessage() {}

func (x *RequestGatewayPush) ProtoReflect() protoreflect.Message {
	mi := &file_bundle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGatewayPush.ProtoReflect.Descriptor instead.
func (*RequestGatewayPush) Descriptor() ([]byte, []int) {
	return file_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGatewayPush) GetTarget() *network.ClientID {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RequestGatewayPush) GetBody() *any.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_bundle_proto protoreflect.FileDescriptor

var file_bundle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x70, 0x72, 0x76, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x64, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x69, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x75, 0x73, 0x68, 0x12, 0x29, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x72, 0x76, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bundle_proto_rawDescOnce sync.Once
	file_bundle_proto_rawDescData = file_bundle_proto_rawDesc
)

func file_bundle_proto_rawDescGZIP() []byte {
	file_bundle_proto_rawDescOnce.Do(func() {
		file_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(file_bundle_proto_rawDescData)
	})
	return file_bundle_proto_rawDescData
}

var file_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bundle_proto_goTypes = []interface{}{
	(*ForwardBundle)(nil),      // 0: prvs.ForwardBundle
	(*RequestGatewayPush)(nil), // 1: prvs.RequestGatewayPush
	(*network.ClientID)(nil),   // 2: network.ClientID
	(*any.Any)(nil),            // 3: google.protobuf.Any
}
var file_bundle_proto_depIdxs = []int32{
	2, // 0: prvs.ForwardBundle.sender:type_name -> network.ClientID
	3, // 1: prvs.ForwardBundle.body:type_name -> google.protobuf.Any
	2, // 2: prvs.RequestGatewayPush.target:type_name -> network.ClientID
	3, // 3: prvs.RequestGatewayPush.body:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bundle_proto_init() }
func file_bundle_proto_init() {
	if File_bundle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bundle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardBundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bundle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGatewayPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bundle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bundle_proto_goTypes,
		DependencyIndexes: file_bundle_proto_depIdxs,
		MessageInfos:      file_bundle_proto_msgTypes,
	}.Build()
	File_bundle_proto = out.File
	file_bundle_proto_rawDesc = nil
	file_bundle_proto_goTypes = nil
	file_bundle_proto_depIdxs = nil
}
