// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package prvs

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
  "github.com/yamakiller/velcro-go/network"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//  - Target
type RequestGatewayCloseClient struct {
  Target *network.ClientID `thrift:"Target,1" db:"Target" json:"Target"`
}

func NewRequestGatewayCloseClient() *RequestGatewayCloseClient {
  return &RequestGatewayCloseClient{}
}

var RequestGatewayCloseClient_Target_DEFAULT *network.ClientID
func (p *RequestGatewayCloseClient) GetTarget() *network.ClientID {
  if !p.IsSetTarget() {
    return RequestGatewayCloseClient_Target_DEFAULT
  }
return p.Target
}
func (p *RequestGatewayCloseClient) IsSetTarget() bool {
  return p.Target != nil
}

func (p *RequestGatewayCloseClient) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayCloseClient)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Target = &network.ClientID{}
  if err := p.Target.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Target), err)
  }
  return nil
}

func (p *RequestGatewayCloseClient) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "RequestGatewayCloseClient"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayCloseClient) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "Target", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:Target: ", p), err) }
  if err := p.Target.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Target), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:Target: ", p), err) }
  return err
}

func (p *RequestGatewayCloseClient) Equals(other *RequestGatewayCloseClient) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if !p.Target.Equals(other.Target) { return false }
  return true
}

func (p *RequestGatewayCloseClient) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayCloseClient(%+v)", *p)
}

func (p *RequestGatewayCloseClient) Validate() error {
  return nil
}
// Attributes:
//  - ClientID
type ClientClosed struct {
  ClientID *network.ClientID `thrift:"ClientID,1" db:"ClientID" json:"ClientID"`
}

func NewClientClosed() *ClientClosed {
  return &ClientClosed{}
}

var ClientClosed_ClientID_DEFAULT *network.ClientID
func (p *ClientClosed) GetClientID() *network.ClientID {
  if !p.IsSetClientID() {
    return ClientClosed_ClientID_DEFAULT
  }
return p.ClientID
}
func (p *ClientClosed) IsSetClientID() bool {
  return p.ClientID != nil
}

func (p *ClientClosed) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ClientClosed)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.ClientID = &network.ClientID{}
  if err := p.ClientID.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ClientID), err)
  }
  return nil
}

func (p *ClientClosed) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "ClientClosed"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ClientClosed) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "ClientID", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ClientID: ", p), err) }
  if err := p.ClientID.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ClientID), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ClientID: ", p), err) }
  return err
}

func (p *ClientClosed) Equals(other *ClientClosed) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if !p.ClientID.Equals(other.ClientID) { return false }
  return true
}

func (p *ClientClosed) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ClientClosed(%+v)", *p)
}

func (p *ClientClosed) Validate() error {
  return nil
}
type ClientClosedService interface {
  // Parameters:
  //  - Req
  OnClientClosed(ctx context.Context, req *ClientClosed) (_err error)
}

type ClientClosedServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewClientClosedServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ClientClosedServiceClient {
  return &ClientClosedServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewClientClosedServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ClientClosedServiceClient {
  return &ClientClosedServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewClientClosedServiceClient(c thrift.TClient) *ClientClosedServiceClient {
  return &ClientClosedServiceClient{
    c: c,
  }
}

func (p *ClientClosedServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *ClientClosedServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *ClientClosedServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// Parameters:
//  - Req
func (p *ClientClosedServiceClient) OnClientClosed(ctx context.Context, req *ClientClosed) (_err error) {
  var _args0 ClientClosedServiceOnClientClosedArgs
  _args0.Req = req
  var _result2 ClientClosedServiceOnClientClosedResult
  var _meta1 thrift.ResponseMeta
  _meta1, _err = p.Client_().Call(ctx, "OnClientClosed", &_args0, &_result2)
  p.SetLastResponseMeta_(_meta1)
  if _err != nil {
    return
  }
  return nil
}

type ClientClosedServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler ClientClosedService
}

func (p *ClientClosedServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *ClientClosedServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *ClientClosedServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewClientClosedServiceProcessor(handler ClientClosedService) *ClientClosedServiceProcessor {

  self3 := &ClientClosedServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self3.processorMap["OnClientClosed"] = &clientClosedServiceProcessorOnClientClosed{handler:handler}
return self3
}

func (p *ClientClosedServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x4 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x4.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x4

}

type clientClosedServiceProcessorOnClientClosed struct {
  handler ClientClosedService
}

func (p *clientClosedServiceProcessorOnClientClosed) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err5 error
  args := ClientClosedServiceOnClientClosedArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "OnClientClosed", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := ClientClosedServiceOnClientClosedResult{}
  if err2 := p.handler.OnClientClosed(ctx, args.Req); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc6 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing OnClientClosed: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "OnClientClosed", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := _exc6.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
      _write_err5 = thrift.WrapTException(err2)
    }
    if _write_err5 != nil {
      return false, thrift.WrapTException(_write_err5)
    }
    return true, err
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "OnClientClosed", thrift.REPLY, seqId); err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err5 == nil && err2 != nil {
    _write_err5 = thrift.WrapTException(err2)
  }
  if _write_err5 != nil {
    return false, thrift.WrapTException(_write_err5)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
type ClientClosedServiceOnClientClosedArgs struct {
  Req *ClientClosed `thrift:"req,1" db:"req" json:"req"`
}

func NewClientClosedServiceOnClientClosedArgs() *ClientClosedServiceOnClientClosedArgs {
  return &ClientClosedServiceOnClientClosedArgs{}
}

var ClientClosedServiceOnClientClosedArgs_Req_DEFAULT *ClientClosed
func (p *ClientClosedServiceOnClientClosedArgs) GetReq() *ClientClosed {
  if !p.IsSetReq() {
    return ClientClosedServiceOnClientClosedArgs_Req_DEFAULT
  }
return p.Req
}
func (p *ClientClosedServiceOnClientClosedArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *ClientClosedServiceOnClientClosedArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ClientClosedServiceOnClientClosedArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &ClientClosed{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *ClientClosedServiceOnClientClosedArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnClientClosed_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ClientClosedServiceOnClientClosedArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *ClientClosedServiceOnClientClosedArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ClientClosedServiceOnClientClosedArgs(%+v)", *p)
}

type ClientClosedServiceOnClientClosedResult struct {
}

func NewClientClosedServiceOnClientClosedResult() *ClientClosedServiceOnClientClosedResult {
  return &ClientClosedServiceOnClientClosedResult{}
}

func (p *ClientClosedServiceOnClientClosedResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    if err := iprot.Skip(ctx, fieldTypeId); err != nil {
      return err
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *ClientClosedServiceOnClientClosedResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnClientClosed_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *ClientClosedServiceOnClientClosedResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("ClientClosedServiceOnClientClosedResult(%+v)", *p)
}


type RequestGatewayCloseClientService interface {
  // Parameters:
  //  - Req
  OnRequestGatewayCloseClient(ctx context.Context, req *RequestGatewayCloseClient) (_r *RequestGatewayCloseClient, _err error)
}

type RequestGatewayCloseClientServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewRequestGatewayCloseClientServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *RequestGatewayCloseClientServiceClient {
  return &RequestGatewayCloseClientServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewRequestGatewayCloseClientServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *RequestGatewayCloseClientServiceClient {
  return &RequestGatewayCloseClientServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewRequestGatewayCloseClientServiceClient(c thrift.TClient) *RequestGatewayCloseClientServiceClient {
  return &RequestGatewayCloseClientServiceClient{
    c: c,
  }
}

func (p *RequestGatewayCloseClientServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *RequestGatewayCloseClientServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *RequestGatewayCloseClientServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// Parameters:
//  - Req
func (p *RequestGatewayCloseClientServiceClient) OnRequestGatewayCloseClient(ctx context.Context, req *RequestGatewayCloseClient) (_r *RequestGatewayCloseClient, _err error) {
  var _args13 RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs
  _args13.Req = req
  var _result15 RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult
  var _meta14 thrift.ResponseMeta
  _meta14, _err = p.Client_().Call(ctx, "OnRequestGatewayCloseClient", &_args13, &_result15)
  p.SetLastResponseMeta_(_meta14)
  if _err != nil {
    return
  }
  if _ret16 := _result15.GetSuccess(); _ret16 != nil {
    return _ret16, nil
  }
  return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "OnRequestGatewayCloseClient failed: unknown result")
}

type RequestGatewayCloseClientServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler RequestGatewayCloseClientService
}

func (p *RequestGatewayCloseClientServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *RequestGatewayCloseClientServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *RequestGatewayCloseClientServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewRequestGatewayCloseClientServiceProcessor(handler RequestGatewayCloseClientService) *RequestGatewayCloseClientServiceProcessor {

  self17 := &RequestGatewayCloseClientServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self17.processorMap["OnRequestGatewayCloseClient"] = &requestGatewayCloseClientServiceProcessorOnRequestGatewayCloseClient{handler:handler}
return self17
}

func (p *RequestGatewayCloseClientServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x18 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x18.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x18

}

type requestGatewayCloseClientServiceProcessorOnRequestGatewayCloseClient struct {
  handler RequestGatewayCloseClientService
}

func (p *requestGatewayCloseClientServiceProcessorOnRequestGatewayCloseClient) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  var _write_err19 error
  args := RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs{}
  if err2 := args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "OnRequestGatewayCloseClient", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelCauseFunc
    ctx, cancel = context.WithCancelCause(ctx)
    defer cancel(nil)
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelCauseFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel(thrift.ErrAbandonRequest)
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult{}
  if retval, err2 := p.handler.OnRequestGatewayCloseClient(ctx, args.Req); err2 != nil {
    tickerCancel()
    err = thrift.WrapTException(err2)
    if errors.Is(err2, thrift.ErrAbandonRequest) {
      return false, thrift.WrapTException(err2)
    }
    if errors.Is(err2, context.Canceled) {
      if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
        return false, thrift.WrapTException(err)
      }
    }
    _exc20 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing OnRequestGatewayCloseClient: " + err2.Error())
    if err2 := oprot.WriteMessageBegin(ctx, "OnRequestGatewayCloseClient", thrift.EXCEPTION, seqId); err2 != nil {
      _write_err19 = thrift.WrapTException(err2)
    }
    if err2 := _exc20.Write(ctx, oprot); _write_err19 == nil && err2 != nil {
      _write_err19 = thrift.WrapTException(err2)
    }
    if err2 := oprot.WriteMessageEnd(ctx); _write_err19 == nil && err2 != nil {
      _write_err19 = thrift.WrapTException(err2)
    }
    if err2 := oprot.Flush(ctx); _write_err19 == nil && err2 != nil {
      _write_err19 = thrift.WrapTException(err2)
    }
    if _write_err19 != nil {
      return false, thrift.WrapTException(_write_err19)
    }
    return true, err
  } else {
    result.Success = retval
  }
  tickerCancel()
  if err2 := oprot.WriteMessageBegin(ctx, "OnRequestGatewayCloseClient", thrift.REPLY, seqId); err2 != nil {
    _write_err19 = thrift.WrapTException(err2)
  }
  if err2 := result.Write(ctx, oprot); _write_err19 == nil && err2 != nil {
    _write_err19 = thrift.WrapTException(err2)
  }
  if err2 := oprot.WriteMessageEnd(ctx); _write_err19 == nil && err2 != nil {
    _write_err19 = thrift.WrapTException(err2)
  }
  if err2 := oprot.Flush(ctx); _write_err19 == nil && err2 != nil {
    _write_err19 = thrift.WrapTException(err2)
  }
  if _write_err19 != nil {
    return false, thrift.WrapTException(_write_err19)
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
type RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs struct {
  Req *RequestGatewayCloseClient `thrift:"req,1" db:"req" json:"req"`
}

func NewRequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs() *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs {
  return &RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs{}
}

var RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs_Req_DEFAULT *RequestGatewayCloseClient
func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) GetReq() *RequestGatewayCloseClient {
  if !p.IsSetReq() {
    return RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs_Req_DEFAULT
  }
return p.Req
}
func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &RequestGatewayCloseClient{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestGatewayCloseClient_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayCloseClientServiceOnRequestGatewayCloseClientArgs(%+v)", *p)
}

// Attributes:
//  - Success
type RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult struct {
  Success *RequestGatewayCloseClient `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewRequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult() *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult {
  return &RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult{}
}

var RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult_Success_DEFAULT *RequestGatewayCloseClient
func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) GetSuccess() *RequestGatewayCloseClient {
  if !p.IsSetSuccess() {
    return RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult_Success_DEFAULT
  }
return p.Success
}
func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  p.Success = &RequestGatewayCloseClient{}
  if err := p.Success.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "OnRequestGatewayCloseClient_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("RequestGatewayCloseClientServiceOnRequestGatewayCloseClientResult(%+v)", *p)
}


